name: Deploy service/og-img-gen

on:
  push:
    branches:
      - "*"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_OG_IMG_GEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/og-img-gen
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
